---
- name: Create a mysql server in the local
  hosts: localhost
  become: yes
  become_method: sudo
  remote_user: root
  tasks:
    - name: Update Repository
      apt:
        update_cache: yes
        state: latest
    - name: install MYSQL client
      apt: name=mysql-client state=latest
    - name: copy file to  server
      shell: scp /root/Ansible-Mysql-client-server-ubuntu/mysqld.cnf ubuntu@ip:/home/ubuntu/mysqld.cnf
